# Generated by Django 5.2.2 on 2026-02-26 03:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import localizador.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf_usuario', models.CharField(max_length=14, unique=True)),
                ('status_usuario', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Arquivo',
            fields=[
                ('id_aluno_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('status_arquivo_aluno', models.CharField(choices=[('A', 'Ativo'), ('P', 'Permanente')], max_length=1)),
                ('cod_sistema', models.IntegerField(unique=True)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('localizacao_arquivo', models.IntegerField(blank=True, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
                ('pessoa_contato', models.CharField(max_length=100)),
                ('aluno_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='localizador.aluno_arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVinculado',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=localizador.models.get_upload_path)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroPassivoDisponivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('A', 'Aluno'), ('P', 'Profissional')], max_length=1)),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('numero', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id_pendencia', models.AutoField(primary_key=True, serialize=False)),
                ('dt_lancamento_pendencia', models.DateField()),
                ('tipo_pendencia', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('aluno_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='localizador.aluno_arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional_Arquivo',
            fields=[
                ('id_profissional_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_profissional', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('status_arquivo_profissional', models.CharField(choices=[('A', 'Ativo'), ('P', 'Permanente')], max_length=1)),
                ('localizacao_arquivo', models.IntegerField(blank=True, null=True, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('Id_numero_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('funcao', models.CharField(max_length=50)),
                ('dt_inicial', models.DateField()),
                ('dt_final', models.DateField()),
                ('tipo_contrato', models.CharField(max_length=1)),
                ('profissional_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='localizador.profissional_arquivo')),
            ],
        ),
    ]
