# Generated by Django 5.2.2 on 2025-06-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(default='teste@email.com', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.CharField(default='admin', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default='Usuário Teste', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_usuario',
            field=models.CharField(default='senha123', max_length=128),
        ),
        migrations.AlterField(
            model_name='aluno_arquivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='localizador.usuario'),
        ),
        migrations.AlterField(
            model_name='profissional_arquivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='localizador.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf_usuario',
            field=models.CharField(default='12345678900', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status_usuario',
            field=models.CharField(max_length=1),
        ),
    ]
