# Generated by Django 5.2.2 on 2025-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizador', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencia',
            name='tipo_pendencia',
            field=models.CharField(max_length=50),
        ),
    ]
